version: 2.1

orbs:
  gcloud: circleci/gcp-cli@3.1.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - sdx-1261

jobs:
  build:
    docker:
      - image: cimg/node:20.12
    environment:
      TURBO_TOKEN: $TURBO_TOKEN
      TURBO_TEAM: $TURBO_TEAM
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y jq
      - gcloud/setup
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable --install-directory ~/bin
            corepack prepare pnpm@latest-8 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - run:
          name: Build bundle
          command: pnpm run build:bundle
      - run:
          name: Copy to bucket
          command: |
            sanity_version=$(cat packages/sanity/package.json | jq -r .version)
            gcloud storage rsync ./packages/sanity/dist $GCLOUD_BUCKET/sanity/$sanity_version --recursive --content-type=application/javascript
